# .gitlab-ci.yml
stages:
  - lint
  - test

pylint:
  stage: lint
  tags:
    - windows
  script:
    - |
      choco install python
      $env:Path = [System.Environment]::ExpandEnvironmentVariables([System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User"))
      & ".\gitlab-test\Scripts\activate.bat"
      pip install pylint
      pylint --fail-under 9.0 ./src
  artifacts:
    when: always
    paths:
      - pylint.log

black:
  stage: lint
  tags:
    - windows
  script:
    - |
      choco install python
      $env:Path = [System.Environment]::ExpandEnvironmentVariables([System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User"))
      & ".\gitlab-test\Scripts\activate.bat"
      pip install black
      black --check --verbose .
  artifacts:
    when: always
    paths:
      - black.log

test:
  stage: test
  tags:
    - windows
  script:
    - |
      choco install python
      $env:Path = [System.Environment]::ExpandEnvironmentVariables([System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User"))
      & ".\gitlab-test\Scripts\activate.bat"
      pip install -r requirements.txt
      python -m unittest discover
  artifacts:
    when: always
    paths:
      - test-results.xml
